version: "3.8"
services:
  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - elasticsearch
    volumes:
      - ./backend:/app
    environment:
      - LOGIN_EMAIL=${LOGIN_EMAIL}
      - LOGIN_PASSWORD=${LOGIN_PASSWORD}

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
